
CREATE TABLE IF NOT EXISTS rates_history
(
    id SERIAL PRIMARY KEY,
    dates DATE NOT NULL,
    "CAD" DEC,
    "HKD" DEC,
    "CYP" DEC,
    "DKK" DEC, 
    "HUF" DEC,
    "CZK" DEC,
    "GBP" DEC,
    "SEK" DEC,
    "LTL" DEC,
    "TRL" DEC,
    "EEK" DEC,
    "JPY" DEC,
    "KRW" DEC,
    "LVL" DEC,
    "CHF" DEC,
    "EUR" DEC,
    "ROL" DEC,
    "BGN" DEC,
    "NZD" DEC,
    "MTL" DEC,
    "NOK" DEC,
    "SIT" DEC,
    "ZAR" DEC,
    "ISK" DEC,
    "SGD" DEC,
    "AUD" DEC,
    "SKK" DEC,
    "PLN" DEC,
    "PHP" DEC,
    "RON" DEC,
    "IDR" DEC,
    "INR" DEC,
    "BRL" DEC,
    "RUB" DEC,
    "HRK" DEC,
    "THB" DEC,
    "MYR" DEC,
    "TRY" DEC,
    "CNY" DEC,
    "MXN" DEC,
    "ILS" DEC
); 